giou: 3.54
model_name: BertATT
bert_vocab_file: "/Users/i052090/Downloads/segmentation/data/bertmany/bert-base-uncased/bert-base-uncased-vocab.txt"
bert_model_dir: "/Users/i052090/Downloads/segmentation/data/bertmany/bert-base-uncased"
data_dir: "../../data/SST-2/"
output_dir: "./output"
log_dir: "./output/logs"
cache_dir: "./output/cache"
seed: 42
max_seq_length: 256
train_batch_size: 64
gradient_accumulation_steps: 1
num_train_epochs: 2
learning_rate: 1e-5
print_step: 2
gpu_ids: "0"
do_lower_case: True
warmup_proportion: 0.1
early_stop: 50
